### ISSUE TITLE
integration doesn't load and reprots ValueError: 255 is not a valid DaikinOutdoorUnitReversingValveStatus

### ISSUE THREAD

**Issue by jensenc** [zlangbert/ha-daikinone#11]
```
  File "/usr/local/lib/python3.11/enum.py", line 1135, in __new__
    raise ve_exc
ValueError: 255 is not a valid DaikinOutdoorUnitReversingValveStatus
```

i have a daikin one
heat pump DZ17VSA421BA
air handler DV47FECD14AA
one touch running 3.2.19

integration doesn't want to load and reports this error

thanks

**Comment by zlangbert** [comment]
Hi @jensenc, thanks for the report. The latest release should have a fix for this case. If you run into any more problems feel free to reopen this issue. Thanks!
