### ISSUE TITLE
V0.4.0 - Update removed ability to measure temperature.

### ISSUE THREAD

**Issue by npstewart87** [zlangbert/ha-daikinone#14]
Everything seems to work after V0.4.0 Update but the most important thing (Temp reading) isnt working. It says the "Entity is not available". 

I tried removing and reinstalling, restarting HA. No luck. 
![Screenshot 2024-01-21 194615](https://github.com/zlangbert/ha-daikinone/assets/110749578/c3b0ecad-2b79-4665-9bf4-dd4da1ee3c00)

Any suggestions to roll this back?

**Comment by zlangbert** [comment]
Not sure what might be going on there. You are saying you tried removing the integration entry entirely, re-adding it, and the climate entity is still unavailable?

Are there any logs from the integration in Settings -> System -> Logs?

**Comment by npstewart87** [comment]
After I upgraded to 0.4, it told me the temperature entity was not available. I went into the entity itself and took a screen shot per the above.

I already manually downloaded the files from 0.3 and replaced the files. Once I restarted, it started working again.

I will goahead and try upgrading again and then check the logs. I will report back once I do so. Shouldnt take long.

**Comment by npstewart87** [comment]
Also, yes - I deleted the integration, restarted, and re-downloaded it and still didnt work.

**Comment by npstewart87** [comment]
Log file attached as a .txt file. In total, there were (3) errors and I copied them into the text file separated by dashes.


[HASS Daikin V04 Log.txt](https://github.com/zlangbert/ha-daikinone/files/14003703/HASS.Daikin.V04.Log.txt)

**Comment by zlangbert** [comment]
Interesting, thanks for the logs. Are you on the latest version of Home Assistant?

**Comment by npstewart87** [comment]
> Interesting, thanks for the logs. Are you on the latest version of Home Assistant?

The first time I installed it I was 1 core update behind. When it didnt work, I did the update. Those logs are from after I did the core update.

All else is up to date.

**Comment by zlangbert** [comment]
From what I can see in the logs, this issue has something to do with the new attribute caching mechanism in Home Assistant. The error is that the entity has no attribute `__attr_target_temperature_high`. The double underscore properties are the backing fields from the [CachedProperties metaclass](https://github.com/home-assistant/core/blob/da1d530889aa2159facfad9cbd7472351ff65079/homeassistant/helpers/entity.py#L283-L284). 

Previous to version 0.4.0 of this integration, the properties were overridden and decorated with `@property`, which probably disabled caching for them, making whatever is causing this not an issue.

It's hard to imagine why you would be seeing this error and I am not. Can you also tell me what Daikin equipment you have and what mode your thermostat is currently set to?

**Comment by jensenc** [comment]
hi,

with 0.4.0 i can load the integration however the thermostat controller is disabled.
```
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 410, in target_temperature_high
    return self._attr_target_temperature_high
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DaikinOneThermostat' object has no attribute '_attr_target_temperature_high'
```

**Comment by zlangbert** [comment]
I think I figured it out. I am going to release 0.4.1 in a moment, please try that and let me know if it fixes it @npstewart87 @jensenc

**Comment by npstewart87** [comment]
> I think I figured it out. I am going to release 0.4.1 in a moment, please try that and let me know if it fixes it @npstewart87 @jensenc 

Excellent. Will do!

To answer your questions I have a DFVE48DP1400AA Air Handler with a DZ6VSA4810 heat pump condenser. My system has been in "cooling mode" but it's cool outside so hasn't ran in a while. Thermostat model is ONEPLUS with software 3.2.19. 

Much appreciated and I'll wait for the update and will update right away.

**Comment by jensenc** [comment]
> I think I figured it out. I am going to release 0.4.1 in a moment, please try that and let me know if it fixes it @npstewart87 @jensenc

yep that fixed it for me.  many thanks @zlangbert !

**Comment by npstewart87** [comment]
FIXED!! Thanks so much for the quick work. 

One question. The humidity displays in a thermostat integration but I've never been able to get it to display any other way. Is it possible to get the humidity to display as a sensor?

Thanks so much again.

**Comment by zlangbert** [comment]
Great, glad we got that fixed. Thank you both!

> One question. The humidity displays in a thermostat integration but I've never been able to get it to display any other way. Is it possible to get the humidity to display as a sensor?

I was debating yesterday whether to add sensors for indoor temp and humidity. Technically its there on the extra attributes of the climate entity. For example you can use a template like `{{ state_attr('climate.upstairs_thermostat', 'current_temperature') }}` to get the value. You could then create a template sensor like:
```
template:
  - sensor:
      # upstairs
      - name: "Upstairs Thermostat current temperature"
        state_class: measurement
        device_class: temperature
        unit_of_measurement: "°F"
        state: >
          {{ state_attr('climate.upstairs_thermostat', 'current_temperature') }}
```
to track it. 

Having said that, I don't see why not just have sensors. I will add them.
